
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package def;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DIVEQ = 35;
  public static final int PLUSPLUS = 26;
  public static final int FUNCTION = 41;
  public static final int MULT = 24;
  public static final int GE = 39;
  public static final int DOUBLE = 16;
  public static final int PRIVATE = 46;
  public static final int LPAREN = 7;
  public static final int INT = 14;
  public static final int ARRAY = 19;
  public static final int FOR = 43;
  public static final int MINUS = 23;
  public static final int RPAREN = 8;
  public static final int OROR = 29;
  public static final int LT = 36;
  public static final int COMMA = 6;
  public static final int DIV = 25;
  public static final int ANDAND = 28;
  public static final int PLUSEQ = 32;
  public static final int MINUSEQ = 33;
  public static final int PLUS = 22;
  public static final int IF = 40;
  public static final int THIS = 21;
  public static final int LE = 38;
  public static final int EOF = 0;
  public static final int BOOLEAN = 17;
  public static final int MINUSMINUS = 27;
  public static final int DICTIONARY = 20;
  public static final int error = 1;
  public static final int EQEQ = 31;
  public static final int MULTEQ = 34;
  public static final int VOID = 18;
  public static final int EQ = 30;
  public static final int SWITCH = 42;
  public static final int LBRACK = 11;
  public static final int COLON = 13;
  public static final int LBRACE = 9;
  public static final int VARIABLE = 5;
  public static final int RBRACK = 12;
  public static final int WHILE = 44;
  public static final int CREATE = 2;
  public static final int PUBLIC = 45;
  public static final int RBRACE = 10;
  public static final int END = 4;
  public static final int STRING = 15;
  public static final int GT = 37;
  public static final int INTEGER_LITERAL = 47;
  public static final int IDENTIFIER = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CREATE",
  "IDENTIFIER",
  "END",
  "VARIABLE",
  "COMMA",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "LBRACK",
  "RBRACK",
  "COLON",
  "INT",
  "STRING",
  "DOUBLE",
  "BOOLEAN",
  "VOID",
  "ARRAY",
  "DICTIONARY",
  "THIS",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "PLUSPLUS",
  "MINUSMINUS",
  "ANDAND",
  "OROR",
  "EQ",
  "EQEQ",
  "PLUSEQ",
  "MINUSEQ",
  "MULTEQ",
  "DIVEQ",
  "LT",
  "GT",
  "LE",
  "GE",
  "IF",
  "FUNCTION",
  "SWITCH",
  "FOR",
  "WHILE",
  "PUBLIC",
  "PRIVATE",
  "INTEGER_LITERAL"
  };
}

