
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package def;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int CREATE = 2;
  public static final int error = 1;
  public static final int IDENTIFIER = 3;
  public static final int END = 4;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CREATE",
  "IDENTIFIER",
  "END"
  };
}

