
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package hu.iit.uni_miskolc.horvath23.Crosstranslator.parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DIVEQ = 35;
  public static final int PLUSPLUS = 26;
  public static final int STRING_LITERAL = 53;
  public static final int FUNCTION = 43;
  public static final int GTEQ = 39;
  public static final int MULT = 24;
  public static final int GE = 41;
  public static final int LTEQ = 37;
  public static final int DOUBLE = 16;
  public static final int PRIVATE = 48;
  public static final int LPAREN = 6;
  public static final int INT = 14;
  public static final int ARRAY = 19;
  public static final int FOR = 45;
  public static final int MINUS = 23;
  public static final int RPAREN = 7;
  public static final int BOOLEAN_LITERAL = 51;
  public static final int OROR = 29;
  public static final int CHARACTER_LITERAL = 52;
  public static final int LT = 36;
  public static final int COMMA = 5;
  public static final int DIV = 25;
  public static final int ANDAND = 28;
  public static final int PLUSEQ = 32;
  public static final int MINUSEQ = 33;
  public static final int PLUS = 22;
  public static final int NULL_LITERAL = 55;
  public static final int IF = 42;
  public static final int THIS = 21;
  public static final int DOT = 13;
  public static final int LE = 40;
  public static final int EOF = 0;
  public static final int BOOLEAN = 17;
  public static final int MINUSMINUS = 27;
  public static final int DICTIONARY = 20;
  public static final int error = 1;
  public static final int EQEQ = 31;
  public static final int MULTEQ = 34;
  public static final int VOID = 18;
  public static final int EQ = 30;
  public static final int SWITCH = 44;
  public static final int LBRACK = 10;
  public static final int COLON = 12;
  public static final int FLOATING_POINT_LITERAL = 50;
  public static final int LBRACE = 8;
  public static final int VARIABLE = 4;
  public static final int RBRACK = 11;
  public static final int WHILE = 46;
  public static final int CREATE = 2;
  public static final int PUBLIC = 47;
  public static final int RBRACE = 9;
  public static final int END = 3;
  public static final int STRING = 15;
  public static final int GT = 38;
  public static final int IDENTIFIER = 54;
  public static final int INTEGER_LITERAL = 49;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CREATE",
  "END",
  "VARIABLE",
  "COMMA",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "LBRACK",
  "RBRACK",
  "COLON",
  "DOT",
  "INT",
  "STRING",
  "DOUBLE",
  "BOOLEAN",
  "VOID",
  "ARRAY",
  "DICTIONARY",
  "THIS",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "PLUSPLUS",
  "MINUSMINUS",
  "ANDAND",
  "OROR",
  "EQ",
  "EQEQ",
  "PLUSEQ",
  "MINUSEQ",
  "MULTEQ",
  "DIVEQ",
  "LT",
  "LTEQ",
  "GT",
  "GTEQ",
  "LE",
  "GE",
  "IF",
  "FUNCTION",
  "SWITCH",
  "FOR",
  "WHILE",
  "PUBLIC",
  "PRIVATE",
  "INTEGER_LITERAL",
  "FLOATING_POINT_LITERAL",
  "BOOLEAN_LITERAL",
  "CHARACTER_LITERAL",
  "STRING_LITERAL",
  "IDENTIFIER",
  "NULL_LITERAL"
  };
}

